SSAnne_B1F_Room5_Text_MachokeHasStrengthToMoveRocks::
    .string "My buddy MACHOKE is super strong!\p"
    .string "He has enough STRENGTH to move\n"
    .string "big rocks!$"

SSAnne_B1F_Room5_Text_Machoke::
    .string "MACHOKE: Gwoh! Goggoh!$"

SSAnne_B1F_Room5_Text_RedVoltorb::
	.string "Something is wrong with this\n"
	.string "Pokemon... it's glowing red.\p"
	.string "It is about to explode!$"
	
SSAnne_B1F_Room5_Text_VoltorbDown::
	.string "The ELECTRODE has fainted.\n"
	.string "It will not explode now.$"
