SSAnne_3F_Corridor_Text_CaptainTeachesCutToMons::
    .string "Our CAPTAIN is a sword master.\n"
    .string "He's awesome at using CUT.\p"
    .string "They say he even teaches CUT\n"
    .string "to POKéMON!$"

SSAnne_3F_Corridor_Text_AquaIntro:: 
	.string "These rich fools deserve\n"
	.string "what's coming to them.$"
	
SSAnne_3F_Corridor_Text_AquaDefeat::
	.string "I sank!$"
	
SSAnne_3F_Corridor_Text_AquaPostBattle::
	.string "Even if you stop us here,\n"
	.string "this boat will go down.$"
