SSAnne_Deck_Text_ShipDepartingSoon::
    .string "The party's over.\n"
    .string "The ship will be departing soon.$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
    .string "Whew!\n"
    .string "Scrubbing decks is hard work!$"

SSAnne_Deck_Text_FeelSeasick::
    .string "Urf… I feel ill…\p"
    .string "I got seasick, so I stepped out to\n"
    .string "get some air…$"

SSAnne_Deck_Text_EdmondIntro::
    .string "Hey, matey!\p"
    .string "Let's do a little jig!$"

SSAnne_Deck_Text_EdmondDefeat::
    .string "You're impressive!$"

SSAnne_Deck_Text_EdmondPostBattle::
    .string "How many kinds of POKéMON do you\n"
    .string "think there are in this big world?$"

SSAnne_Deck_Text_TrevorIntro::
    .string "Ahoy, there!\n"
    .string "Are you seasick?$"

SSAnne_Deck_Text_TrevorDefeat::
    .string "I was just careless!$"

SSAnne_Deck_Text_TrevorPostBattle::
    .string "My pa said there are 100 kinds of\n"
    .string "POKéMON. I think there are more.$"

SSAnne_Deck_Text_DukeIntro::
	.string "You seem to meddle in\n"
	.string "everyone's plans. Yes I heard\p"
	.string "about you from my allies you\n"
	.string "encountered in MT. MOON. I will\p"
	.string "succeed where they failed.$"
	
SSAnne_Deck_Text_DukeDefeat::
	.string "Impossible!$"

SSAnne_Deck_Text_DukePostBattle::
	.string "Foiled by a child. I will\n"
	.string "get my revenge on you in time.\p"
	.string "For now, we are gone.$"
