Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hi!\n"
    .string "I work at a POKéMON MART.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in VIRIDIAN CITY.\p"
    .string "I know, I'll give you a sample.\n"
    .string "Here you go!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Please come see us if you need\n"
    .string "POKé BALLS for catching POKéMON.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's ITEMS POCKET.$"

Route1_Text_CanJumpFromLedges::
    .string "See those ledges along the road?\p"
    .string "It's a bit scary, but you can jump\n"
    .string "from them.\p"
    .string "You can get back to PALLET TOWN\n"
    .string "quicker that way.$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "PALLET TOWN - VIRIDIAN CITY$"

Route1_Text_CrystalIntro::
	.string "Viridian City is just up ahead.\n"
	.string "Make sure to stop by the Pokemon\p"
	.string "Center to heal your Pokemon.$"
	
Route1_Text_CrystalBattle::
	.string "Oh, a new trainer.\n"
	.string "When trainer's lock eyes\p"
	.string "they must battle.$"
	
Route1_Text_CrystalDefeat::
	.string "Excellent!\n"
	.string "You're as good as I hoped.$"
	
Route1_Text_CrystalPostBattle::
	.string "My name is Crystal and I am\n"
	.string "here working for Prof. Oak with\p"
	.string "his research.  I am sure we will\n"
	.string "meet again.$"
