CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
    .string "Hi!\n"
    .string "Welcome to our BIKE SHOP.\p"
    .string "Have we got just the BIKE for\n"
    .string "you!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
    .string "Sorry!\n"
    .string "You can't afford it!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
    .string "Oh, that's…\p"
    .string "A BIKE VOUCHER!\p"
    .string "Okay!\n"
    .string "Here you go!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
    .string "{PLAYER} exchanged the\n"
    .string "BIKE VOUCHER for a BICYCLE.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
    .string "Thank you!\n"
    .string "Come back again sometime!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
    .string "How do you like your new BICYCLE?\n"
    .string "Do you like how it rides?\p"
    .string "You can take it out on CYCLING\n"
    .string "ROAD and even into caves!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
    .string "You better make room for your\n"
    .string "BICYCLE!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
    .string "A plain city bike is good enough\n"
    .string "for me.\p"
    .string "After all, you can't put a shopping\n"
    .string "basket on a mountain bike.$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
    .string "These bikes are cool, but they're\n"
    .string "way expensive!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
    .string "Wow.\n"
    .string "Your BIKE is really cool!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket::
    .string "ついに　はつばい！\p"
    .string "ドイツ　せい　さいこうきゅう\n"
    .string "おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
    .string "A shiny new BICYCLE!$"

CeruleanCity_BikeShop_Text_BrawlyIntro::
	.string "Oh, are you interested in a bike?\n" 
	.string "Me too. They are great for staying\p"
	.string "active. Speaking of active, you're\n"
	.string "a Pokemon trainer, right? I need to\p"
	.string "warm up first. How about a quick\n" 
	.string "battle.$"

CeruleanCity_BikeShop_Text_BrawlyDefeat::
	.string "Oh wow, that was invigorating!\n" 
	.string "I have not had this much fun in\p" 
	.string "a long time. I want you to have\n"
	.string "something.$"

CeruleanCity_BikeShop_Text_BrawlyPostBattle::
	.string "There are six of us still around.\n"
	.string "If you fancy a challenge, look in\p" 
	.string "every city for one of them. See ya.$"
	
CeruleanCity_BikeShop_Text_ReceivedTM08::
	.string "You got TM08!$"

CeruleanCity_BikeShop_Text_ExplainTM08::
	.string "That move is BULK UP.  It increases\n" 
	.string "ATTACK and DEFENSE. My name is \p"
	.string "Brawly from Hoenn. A bunch of us gym\n" 
	.string "leaders came over to Kanto to explore\p" 
	.string "the rest of the Pokemon world.$" 
