DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel::
    .string "Well, isn't this a surprise!\n"
    .string "DIGLETT dug this long tunnel!\p"
    .string "It goes right to VIRIDIAN CITY,\n"
    .string "they tell me.$"

DiglettsCave_SouthEntrance_Text_BrendanIntro::
	.string "Wow, 3 badges now.\n"
	.string "I guess you are that much\p"
	.string "tougher now. Let's see.$"

DiglettsCave_SouthEntrance_Text_BrendanDefeat::
	.string "Amazing as always.$"

DiglettsCave_SouthEntrance_Text_BrendanPostBattle::
	.string "Keep going through this cave\n"
	.string "to get back to PEWTER CITY.\p"
	.string "I think someone was looking\n"
	.string "for you over there. He looked\p"
	.string "really nerdy. A scientist,\n"
	.string "maybe. See ya.$"
