Route2_Text_RouteSign::
    .string "ROUTE 2\n"
    .string "VIRIDIAN CITY - PEWTER CITY$"

Route2_Text_DiglettsCave::
    .string "DIGLETT'S CAVE$"

Route2_Text_HenryIntro::
	.string "Bugs are an amazing species.\n"
	.string "They grow strong young.\p"
	.string "Let me show you.$"

Route2_Text_HenryDefeat::
	.string "My bug Pokemon!\n"
	.string "How could I lose?$"
	
Route2_Text_HenryPostBattle::
	.string "I guess it would help to evolve\n "
	.string "them.$"
	
Route2_Text_OpheliaIntro::
	.string "I just got through the forest\n"
	.string "and I still need to train to\p"
	.string "face Brock. Let me test myself\n"
	.string "against you.$"

Route2_Text_OpheliaDefeat::
	.string "Oh, you're tough.\n"
	.string "I can't let this set me back.$"
	
Route2_Text_OpheliaPostBattle::
	.string "I will keep training here but\n "
	.string "you should go face Brock.$"
